SOSADnD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dice/', include('manage_dices.urls')),
    path('heroes/', include('manage_lists.urls')),
    path('', include('main_man.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main_man/urls.py
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from . import views

app_name = 'main_man'

extra_settings = [
    path('delete/', views.DeleteUserView.as_view(), name='delete_account'),
    path('update/', views.UpdateAccountView.as_view(), name='update_settings'),
    path('', views.SettingsView.as_view(), name='account_settings'),
]

urlpatterns = [
    path('reset', views.ResetPasswordPageView.as_view(), name='reset_psw'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('user/', views.AccountView.as_view(), name='account_page'),
    path('settings/', include(extra_settings)),
    path('user/logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('', views.IndexView.as_view(), name='index_page'),
]

manage_dices/urls.py
from django.urls import path
from . import views

app_name = 'manage_dices'

urlpatterns = [
    path('add/', views.add_preset, name='save_preset'),
    path('delete_preset/', views.delete_preset, name='delete_preset'),
    path('roll/', views.get_rolling_result, name='inreg_roll_dices'),
    path('', views.DicePageView.as_view(), name='roll_page'),
]

manage_lists/urls.py
from django.urls import include, path

from . import views

app_name = 'manage_lists'

extra_global_collection_patterns = [
    path('get_pdf/<str:list_uuid>/', views.get_pdf, name='get_pdf'),
    path('like/', views.like_hero, name='like_hero'),
    path('add/', views.add_hero, name='add_hero'),
    path('delete/', views.delete_global_hero, name='delete_global_hero'),
    path('', views.see_global_collection, name='collection'),
]

extra_locale_collection_patterns = [
    path('get_pdf/<str:list_uuid>/', views.get_pdf, name='get_pdf'),
    path('delete/', views.delete_local_hero, name='delete_local_hero'),
    path('edit/<str:list_uuid>/', views.edit_hero, name='edit_hero'),
    path('publish/', views.publish_hero, name='publish_hero'),
    path('', views.see_locale_collection, name='locale_collection'),
]

urlpatterns = [
    path('collection/', include(extra_global_collection_patterns)),
    path('my_heroes/', include(extra_locale_collection_patterns)),
    path('new_hero/', views.create_hero, name='create_hero'),
    path('save_hero/', views.save_created_hero, name='save_hero'),
    path('', views.create_hero, name='create_hero'),
]

main_man/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models


class CustomUserManager(BaseUserManager):
    def create_user(self, username, email='', password=None):
        if not username:
            raise ValueError('Users must have a username')

        user = self.model(username=username, email=email)
        user.save()
        return user

    def create_superuser(self, username, email='', password=None):
        user = self.create_user(username, email, password)
        user.is_staff = True
        user.is_superuser = True
        user.set_password(password)
        user.save()
        return user


class CustomUser(AbstractBaseUser):
    username = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=255)
    email = models.EmailField(blank=True, default='', unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    last_login = models.DateField(auto_now=True)
    date_joined = models.DateField(auto_now_add=True)

    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'

    objects = CustomUserManager()

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def __str__(self):
        return self.username

    def __repr__(self):
        return f"{self.username}, {self.email}"

main_man/forms.py
from django.core.exceptions import ValidationError as CoreValidationError, ObjectDoesNotExist
from django.contrib.auth.hashers import is_password_usable
from django.forms import CharField, Form, PasswordInput, ValidationError
from django.utils.translation import ugettext_lazy as _

from users.models import CustomUser


class LoginForm(Form):
    username = CharField(max_length=30)
    password = CharField(max_length=32, widget=PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username']

        if len(username) > 30:
            raise ValidationError(_('Username is too long - username must be contain no more than 30 symbols'))
        if not username:
            raise ValidationError(_('Empty username - username must be specified'))
        return username


class RegisterForm(Form):
    new_username = CharField(max_length=30)
    psw_1 = CharField(max_length=32, widget=PasswordInput)
    psw_2 = CharField(max_length=32, widget=PasswordInput)

    def clean_new_username(self):
        new_user_username = self.cleaned_data['new_username']

        if not new_user_username:
            raise ValidationError(_('Empty username - username must be specified'))
        if CustomUser.objects.filter(username=new_user_username).exists():
            raise ValidationError(_('Existing username - username must be unique'))
        if len(new_user_username) > 30:
            raise ValidationError(_('Username is too long - username must be contain no more than 30 symbols'))
        return new_user_username

    def clean(self):
        cleaned_data = super().clean()
        psw_1 = cleaned_data.get("psw_1")
        psw_2 = cleaned_data.get("psw_2")

        if len(psw_1) != len(psw_2) or psw_1 != psw_2:
            raise ValidationError(_('Wrong repetition - passwords don\'t match'))
        if len(psw_1) < 6 or len(psw_2) < 6:
            raise ValidationError(_('Short password - password must be at least six symbols'))
        if not is_password_usable(psw_1):
            raise ValidationError(_('Password unusable - think up more complex password'))


def validate_email(email):
    if email and '@' not in email:
        raise CoreValidationError(_(f'{email} is incorrect email'),
                                  params={'email': email},)


class AccountSettingsForm(Form):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super(AccountSettingsForm, self).__init__(*args, **kwargs)

    username = CharField(max_length=30, required=False)
    email = CharField(max_length=80, required=False, validators=[validate_email])
    psw_1 = CharField(max_length=32, widget=PasswordInput, required=False)
    psw_2 = CharField(max_length=32, widget=PasswordInput, required=False)

    def clean_username(self):
        username = self.cleaned_data['username']
        # if username does not specified - keep current username
        if not username:
            return username

        try:
            # if there is other with specified username - raise it, else - pass
            user = CustomUser.objects.get(username=username)
            if user.id != self.user.id:
                raise ValidationError(_('Existing username - username must be unique'))
        except ObjectDoesNotExist:
            pass

        if len(username) > 30:
            raise ValidationError(_('Username is too long - username must be contain no more than 30 symbols'))
        return username

    def clean(self):
        cleaned_data = super().clean()
        psw_1 = cleaned_data.get("psw_1")
        psw_2 = cleaned_data.get("psw_2")
        if not psw_1 or not psw_2:
            return
        if psw_1 != psw_2:
            raise ValidationError(_('Wrong repetition - passwords don\'t match'))
        if len(psw_1) < 6 or len(psw_2) < 6:
            raise ValidationError(_('Short password - password must be at least six symbols'))
        if not is_password_usable(psw_1):
            raise ValidationError(_('Password unusable - think up more complex password'))

main_man/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import auth
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import generic
from users.models import CustomUser
from .forms import LoginForm, RegisterForm, AccountSettingsForm


class ResetPasswordPageView(generic.TemplateView):
    template_name = "main_man/reset_password.html"


class DeleteUserView(generic.DeleteView):
    model = CustomUser
    success_url = '/'

    def get_object(self, queryset=None):
        try:
            return CustomUser.objects.get(pk=self.request.user.pk)
        except CustomUser.DoesNotExist:
            raise PermissionError('This user does not exist or you have not permissions')


class SettingsView(generic.TemplateView):
    template_name = "main_man/account_settings.html"

    def get_context_data(self, **kwargs):
        context = super(SettingsView, self).get_context_data(**kwargs)
        prev_data = {
            "username": self.request.user.username,
            "email": self.request.user.email,
        }
        context['account_settings_form'] = AccountSettingsForm(self.request.POST, self.request.user, initial=prev_data)
        return context

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse('main_man:index_page'))
        return render(request, self.template_name, context=self.get_context_data())


class UpdateAccountView(generic.View):
    def post(self, request):
        account_settings_form = AccountSettingsForm(request.POST, user=request.user)
        if account_settings_form.is_valid():
            username = account_settings_form.cleaned_data['username']
            email = account_settings_form.cleaned_data['email']
            psw_1 = account_settings_form.cleaned_data['psw_1']

            me = get_object_or_404(CustomUser, id=request.user.pk)
            me.username = username if username else me.username
            me.email = email if email else me.email
            if psw_1:
                me.password = make_password(psw_1)
            me.save()
            return redirect(reverse('main_man:account_page'))
        else:
            print("Error")
            print(account_settings_form.errors.as_json())
            return render(request, SettingsView.template_name, context={
                "account_settings_form": account_settings_form,
            })


class RegisterView(generic.View):
    def post(self, request):
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            username = register_form.cleaned_data['new_username']
            psw1 = register_form.cleaned_data['psw_1']
            encrypt_password = make_password(psw1)
            CustomUser(username=username, password=encrypt_password).save()
            user = auth.authenticate(username=username, password=psw1)
            auth.login(request, user)
            return redirect(reverse('main_man:account_page'))
        else:
            return render(request, 'main_man/index.html', context={
                "login_form": LoginForm(self.request.POST),
                "register_form": register_form,
            })


class MyLoginView(LoginView):
    def post(self, request, *args, **kwargs):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            name = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = auth.authenticate(username=name, password=password)
            if user is not None:
                if user.is_active:
                    auth.login(request, user)
                    return redirect(reverse('main_man:account_page'))
        return redirect(reverse('main_man:index_page'))


@method_decorator(login_required, name='dispatch')
class AccountView(generic.TemplateView):
    template_name = 'main_man/main_account_page.html'


class IndexView(generic.TemplateView):
    template_name = 'main_man/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['login_form'] = LoginForm()
        context['register_form'] = RegisterForm()
        return context

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse('main_man:account_page'))
        return render(request, self.template_name, context=self.get_context_data())

main_man/templates/main_man/account_settings.html
{% extends 'base_page_struct.html' %}

{% block title %}
    Настройки аккаунта {{ request.user.username }}
{% endblock title %}

{% block link_css %}
    {{ block.super }}

    {% load static %}
    <link rel="stylesheet" href="{% static 'main_man/css/account_settings.css' %}">
{% endblock link_css %}


{% block content %}
    {% load static %}
    <div class="container-fluid">

        <div class="row py-2 my-2">
            <h2 class="col-12">Управление аккаунтом {{ request.user.username }}</h2>
        </div>

        <form method="post">

        </form>

        <div class="row align-items-center justify-content-between my-3">
            <div class="col-12">
                <label class="m-0" for="{{ account_settings_form.username.id_for_label }}">Имя:</label>
            </div>
            <div class="col col-md-8 col-lg-5 col-xl-3 settingsInputWrapper">
                <input type="text"
                       id="{{ account_settings_form.username.id_for_label }}"
                       value="{{ request.user.username }}"
                       class="w-100"
                       maxlength="30" />
            </div>
            <div class="col col-md-8 col-lg-5 col-xl-3">
                {{ account_settings_form.username.errors }}
            </div>
        </div>


        <div class="row align-items-center justify-content-between my-3">
            <div class="col-12">
                <label class="m-0" for="{{ account_settings_form.email.id_for_label }}">Почтовый адрес:</label>
            </div>
            <div class="col col-md-8 col-lg-5 col-xl-3 settingsInputWrapper">
                <input type="email"
                       id="{{ account_settings_form.email.id_for_label }}"
                       value="{{ request.user.email }}"
                       class="w-100 settingsInput"/>
            </div>
            <div class="col col-md-8 col-lg-5 col-xl-3">
                {{ account_settings_form.email.errors }}
            </div>
        </div>

        <div class="row align-items-center justify-content-between my-3">
            <div class="col-12">
                <label class="m-0" for="{{ account_settings_form.psw_1.id_for_label }}">Новый пароль:</label>
            </div>
            <div class="col col-md-8 col-lg-5 col-xl-3 settingsInputWrapper">
                <input type="text"
                       id="{{ account_settings_form.psw_1.id_for_label }}"
                       class="w-100 settingsInput"/>
            </div>
            <div class="col col-md-8 col-lg-5 col-xl-3">
                {{ account_settings_form.psw_1.errors }}
            </div>
        </div>

        <div class="row align-items-center justify-content-between my-3">
            <div class="col-12">
                <label class="m-0" for="{{ account_settings_form.psw_2.id_for_label }}">Повторите новый пароль:</label>
            </div>
            <div class="col col-md-8 col-lg-5 col-xl-3 settingsInputWrapper">
                <input type="text"
                       id="{{ account_settings_form.psw_2.id_for_label }}"
                       class="w-100 settingsInput"/>
            </div>
            <div class="col col-md-8 col-lg-5 col-xl-3">
                {{ account_settings_form.psw_2.errors }}
            </div>
        </div>


        <div class="row mt-2">
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 my-2">
                <button type="button" class="btn btn-success w-100" id="UPDATE_SETTINGS_BTN">Сохранить изменения
                </button>
            </div>
        </div>
        <div class="row mb-2">
            {{ account_settings_form.non_field_errors }}
        </div>

        <div class="row py-2 my-2">
            <div class="col col-md-auto">
                <input type="submit"
                       class="main-action-btn bg-danger"
                       value="Удалить аккаунт"
                       id="DELETE_ACCOUNT_BTN"/>
            </div>
        </div>
    </div>
{% endblock content %}


{% block integrated_js %}
    {{ block.super }}
    <script>

        $("#UPDATE_SETTINGS_BTN").click(function (event) {
            event.preventDefault();
            let data = {};
            data["csrfmiddlewaretoken"] = getCookie('csrftoken');
            data["username"] = $("#id_username").val();
            data["email"] = $("#id_email").val();
            data["psw_1"] = $("#id_psw_1").val();
            data["psw_2"] = $("#id_psw_2").val();

            $.post("{% url 'main_man:update_settings' %}", data, function (data) {
                alert("Data saved");
                window.location.reload();
            });
        });


        $("#DELETE_ACCOUNT_BTN").click(function (event) {
            event.preventDefault();
            let confirmToDelete = confirm("Вы действительно хотите удалить аккаунт?");
            if(confirmToDelete) {
                $.post("{% url 'main_man:delete_account' %}", {"csrfmiddlewaretoken": getCookie('csrftoken')}, function (data) {
                    window.location.href = "/";
                });
            }
        });
    </script>

{% endblock integrated_js %}

main_man/templates/main_man/main_account_page.html
{% extends 'base_page_struct.html' %}


{% block title %}
Профиль {{ request.user.username }}
{% endblock title %}


{% block link_css %}
{{ block.super }}

{% load static %}
<link rel="stylesheet" href="{% static '/main_man/css/main-style.css' %}">
{% endblock link_css %}


{% block content %}
{{ block.super }}
{% load static %}

<div class="container-fluid">
    <div class="row py-2">
        <div class="col-sm-12 col-md-6 col-lg-3 mb-1 px-0 px-md-3">
            <a href="{% url 'manage_dices:roll_page' %}" class="indexPageMenu-item">
                <svg class="indexPageMenu-item_svg" viewBox="15 18 185 228" fill="#eec500">
                    <use xlink:href="#diceIcon"></use>
                </svg>
                <h2 class="pr-3 pl-3">БРОСИТЬ КОСТИ</h2>
                <p>В этом разделе вы можете бросить необходимые комбинации кубиков и сохранить их для быстрого
                    доступа</p>
            </a>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 mb-1 px-0 px-md-3">
            <a href="{% url 'manage_lists:locale_collection' %}" class="indexPageMenu-item">
                <svg class="indexPageMenu-item_svg" viewBox="28 0 160 210" fill="#eec500">
                    <use xlink:href="#localIcon"></use>
                </svg>
                <h2 class="pr-3 pl-3">ЛОКАЛЬНАЯ КОЛЛЕКЦИЯ</h2>
                <p>Здесь вы можете управлять своими листами персонажей</p>
            </a>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 mb-1 px-0 px-md-3">
            <a href="{% url 'manage_lists:collection' %}" class="indexPageMenu-item">
                <svg class="indexPageMenu-item_svg" viewBox="-130 13 245 275" fill="#eec500">
                    <use xlink:href="#globalIcon"></use>
                </svg>
                <h2 class="pr-3 pl-3">ГЛОБАЛЬНАЯ КОЛЛЕКЦИЯ</h2>
                <p>Здесь вы можете просматривать опубликованные пользователями листы персонажей</p>
            </a>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 mb-1 px-0 px-md-3">
            <a href="{% url 'manage_lists:create_hero' %}" class="indexPageMenu-item">
                <svg class="indexPageMenu-item_svg" viewBox="-40 -4 202 214">
                    <use xlink:href="#id_hero_creator"></use>
                </svg>
                <h2 class="pr-3 pl-3">СОЗДАТЬ ПЕРСОНАЖА</h2>
                <p>Заполните новый лист персонажа</p>
            </a>
        </div>
    </div>
</div>

{% endblock content %}

main_man/templates/main_man/reset_password.html
{% extends 'base_page_struct.html' %}

{% block title %}
Восстановление пароля
{% endblock title %}

{% block header_menu %}
<!-- keep empty-->
{% endblock header_menu %}

{% block content %}

<div class="container-fluid">
    <h1 class="mt-5 text-center">Восстановление доступа к аккаунту</h1>
    <p class="text-center mb-5 text-danger">На стадии разработки!!!</p>
    <p class="text-center">Введите адрес электронной почты</p>
    <div class="row justify-content-center">
        <div class="col col-sm-6 col-md-4 col-lg-3">
            <input class="w-100" type="email" value=""/>
        </div>
    </div>
    <div class="row my-2 justify-content-center">
        <div class="col col-sm-6 col-md-4 col-lg-3">
            <input class="w-100 main-action-btn" type="button" value="Продолжить" />
        </div>
    </div>
    <div class="text-center">
        <a href="{% url 'main_man:index_page' %}">Вернуться на главную</a>
    </div>
</div>
{% endblock content %}