SOSADnD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dice/', include('manage_dices.urls')),
    path('heroes/', include('manage_lists.urls')),
    path('', include('main_man.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

manage_dices/urls.py
from django.urls import path
from . import views

app_name = 'manage_dices'

urlpatterns = [
    path('add/', views.add_preset, name='save_preset'),
    path('delete_preset/', views.delete_preset, name='delete_preset'),
    path('roll/', views.get_rolling_result, name='inreg_roll_dices'),
    path('', views.DicePageView.as_view(), name='roll_page'),
]

manage_dices/models.py
import random
import uuid

from django.conf import settings
from django.db import models


def str_to_int(input_str=None):
    """
    Function transforms string to int-type.
    :param input_str: input-string
    :return: number or 0 if string is wrong
    """
    try:
        return int(input_str)
    except TypeError:
        return 0
    except ValueError:
        return 0


class CubesQuerySet(models.QuerySet):
    def personal_presets(self, user):
        return self.filter(user=user)


class CubesManager(models.Manager):
    def get_queryset(self):
        return CubesQuerySet(self.model, using=self._db)

    def personal_presets(self, user):
        return self.get_queryset().personal_presets(user)

    def does_preset_exist(self, user, **preset):
        return self.filter(
            user=user,
            d4=preset['d4'],
            d6=preset['d6'],
            d8=preset['d8'],
            d10=preset['d10'],
            d12=preset['d12'],
            d20=preset['d20'],
        ).exists()


class Cubes(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True,
                             verbose_name='preset owner')
    d4 = models.SmallIntegerField(default=0)
    d6 = models.SmallIntegerField(default=0)
    d8 = models.SmallIntegerField(default=0)
    d10 = models.SmallIntegerField(default=0)
    d12 = models.SmallIntegerField(default=0)
    d20 = models.SmallIntegerField(default=0)
    cube_uuid = models.UUIDField(unique=True, default=uuid.uuid4, blank=False)
    objects = CubesManager()

    ACCEPTABLE_DICES_FIELDS = ['d4', 'd6', 'd8', 'd10', 'd12', 'd20']
    DICES_TYPES = [4, 6, 8, 10, 12, 20]
    MAX_PRESET_SUM = 999

    def set_preset_values(self, preset_config):
        """
        Function sets values from raw configuration to fields.
        :param preset_config: raw preset configuration (list)
        :return: if preset configuration is None raises ValueError,
        return True if fields filled successfully
        """
        if preset_config is None:
            raise ValueError('Preset configuration is empty!')
        # change all non-int type data to 0
        preset_config = self.clean_data(preset_config)
        # set values in model fields
        self.d4 = preset_config['d4']
        self.d6 = preset_config['d6']
        self.d8 = preset_config['d8']
        self.d10 = preset_config['d10']
        self.d12 = preset_config['d12']
        self.d20 = preset_config['d20']

    def eval_rolling_result(self):
        """
        Functions returns random integer value based on preset's configuration.
        :return: int number
        """
        result_sum = 0
        dice_type = self.DICES_TYPES
        for (index, t_dice) in enumerate(self.ACCEPTABLE_DICES_FIELDS):
            for _ in range(self.__getattribute__(t_dice)):
                result_sum += random.randint(1, dice_type[index])
        return result_sum

    def is_preset_valid(self):
        """
        Function checks preset has permissible values.
        Preset must contain positive numbers and be less than MAX_PRESET_SUM (const).
        :return: boolean value shows if preset allowable to use
        """
        max_result_sum = 0
        for (index, t_dice) in enumerate(self.ACCEPTABLE_DICES_FIELDS):
            dice_val = self.__getattribute__(t_dice)
            if dice_val < 0:
                return False
            max_result_sum += self.DICES_TYPES[index] * dice_val

        return 0 < max_result_sum < self.MAX_PRESET_SUM

    @staticmethod
    def clean_data(preset_config):
        """
        Function cleans preset's configuration using str_to_int function.
        :param preset_config: raw preset configuration
        :return: cleaned preset configuration
        """
        for (t_dice, dice_val) in preset_config.items():
            preset_config[t_dice] = str_to_int(dice_val)
        return preset_config

    def __repr__(self):
        return f"Cubes {self.cube_uuid}"

    def __str__(self):
        return f"{self.user}:{self.d4}./.{self.d6}./.{self.d8}./.{self.d10}./.{self.d12}./.{self.d20}"

    class Meta:
        ordering = ['user']

manage_dices/forms.py
from django.forms import ModelForm
from . import models


class PresetForm(ModelForm):
    class Meta:
        model = models.Cubes
        fields = ['d4', 'd6', 'd8', 'd10', 'd12', 'd20']

manage_dices/views.py
import json

from django.contrib.auth.decorators import login_required
from django.http import Http404, JsonResponse
from django.shortcuts import get_object_or_404
from django.views.generic import ListView

from users.models import CustomUser
from .models import Cubes


@login_required
def add_preset(request):
    """
    Function adds new preset-configuration in database Cubes and save it.
    :param request: HTTP request
    :return: JsonResponse object
    """
    if not (request.method == "POST"):
        raise Http404
    new_preset = Cubes(user=request.user)
    raw_preset_config = json.loads(request.POST.get("preset", None))
    new_preset.set_preset_values(raw_preset_config)
    if not new_preset.is_preset_valid():
        return JsonResponse({"dice_error": "Вы ввели некорректное значение!\nВыставьте другие значения."})

    if Cubes.objects.does_preset_exist(
            user=new_preset.user,
            d4=new_preset.d4,
            d6=new_preset.d6,
            d8=new_preset.d8,
            d10=new_preset.d10,
            d12=new_preset.d12,
            d20=new_preset.d20
    ):
        return JsonResponse({"dice_error": "Данная конфигурация уже существует!\nВыставьте другие значения."})
    new_preset.save()
    return JsonResponse({})


@login_required
def delete_preset(request):
    """
    Function removes the existing preset-configuration in database.
    :param request: Http request
    :return: redirect to /dice/
    """
    cube_uuid = json.loads(request.POST.get("cube_uuid", None))
    if cube_uuid is None:
        raise Http404
    get_object_or_404(Cubes, user=request.user, cube_uuid=cube_uuid).delete()
    return JsonResponse({})


def get_rolling_result(request):
    """
    Function returns rolling result.
    :param request: HTTP request
    :return: JsonResponse object
    """
    # return roll for anonym-user
    if not request.user.is_authenticated:
        return roll_unsaved_preset(request, CustomUser(username="Anonymous"))

    # if there is a saved-preset - roll it, else roll unsaved preset
    cube_uuid = request.POST.get("cube_uuid", None)
    if not cube_uuid:
        return roll_unsaved_preset(request, request.user)
    calculated_preset = get_object_or_404(Cubes, user=request.user, cube_uuid=json.loads(cube_uuid))
    return JsonResponse({"result": calculated_preset.eval_rolling_result()})


def roll_unsaved_preset(request, user):
    new_preset = Cubes(user=user)
    raw_preset_config = request.POST.get("preset", None)
    if not raw_preset_config:
        return JsonResponse({"dice_error": "Вы ввели некорректное значение!\nВыставьте другие значения."})
    raw_preset_config_serialised = json.loads(raw_preset_config)
    new_preset.set_preset_values(raw_preset_config_serialised)
    if new_preset.is_preset_valid():
        return JsonResponse({"result": new_preset.eval_rolling_result()})
    return JsonResponse({"dice_error": "Вы ввели некорректное значение!\nВыставьте другие значения."})


class DicePageView(ListView):
    context_object_name = 'presets'
    template_name = 'manage_dices/Dops.html'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Cubes.objects.personal_presets(user=self.request.user)
        return []

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DicePageView, self).get_context_data(**kwargs)
        context['DICES_TYPES'] = Cubes.DICES_TYPES
        return context

manage_dices/templates/manage_dices/Dops.html
{% extends 'base_page_struct.html' %}


{% block title %}
Броски SOSADnD - Найдите свою лучшую конфигурацию броска
{% endblock title %}


{% block content %}
{% load static %}
<div class="container-fluid">

    <div class="row my-3">
        {% for item in DICES_TYPES %}
        <div class="col-sm-4 col-lg-2 p-0 p-sm-3 py-2">
            <div style="min-width: 150px; background: #737373;">
                {% load static %}
                <img class="img-fluid m-auto" src="{% static '/manage_dices/images/dices/d' %}{{ item }}.png"
                     style="max-height: 200px;"/>
                <label class="w-100 p-2" for="preset_d{{item}}">Колличество d{{ item }}:</label>
                <input class="w-100 text-center" id="preset_d{{item}}" type="number"/>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row no-gutters my-5 d-flex align-items-center position-relative">

        <p class="col-12 col-sm-auto">ВАШ&nbsp;РЕЗУЛЬТАТ: </p>

        <div class="thrown-dice-container">
            <div class="back side"><p class="edge">11</p></div>
            <div class="left side"><p class="edge">3</p></div>
            <div class="right side"><p class="edge">17</p></div>
            <div class="top side"><p class="edge">13</p></div>
            <div class="bottom side"><p class="edge">21</p></div>
            <div class="front side"><p id="result" class="edge">0</p></div>
        </div>
        <input class="col-12 col-sm-auto ml-auto main-action-btn p-2 px-4" id="roll_btn" type="button" value="БРОСИТЬ"/>
    </div>

    {% if user.is_authenticated %}
    <div class="row py-3" id="ALL-DICE-COMBINATIONS">
        <div class="col-auto my-2 px-0 px-sm-3" style="min-width: 200px; max-width: 300px;  min-height: 240px;">
            <div class="h-100 position-relative p-2" style="background: #0d0d0d; color: #aaa;">
                <span class="d-block text-right">Добавить</span>
                <span class="d-block text-right">комбинацию</span>
                <input class="w-100 position-absolute fixed-bottom main-action-btn" id="savePresetBtn" type="button" value="СОХРАНИТЬ"/>
            </div>
        </div>


        {% for i in presets %}
        <div class="col-auto my-2 px-0 px-sm-3" style="min-width: 200px; max-width: 300px; min-height: 240px;">

            <div class="h-100 position-relative preset" cube_uuid="{{ i.cube_uuid }}">
                <div class="row w-100 m-auto pt-2 pb-2">
                    <a href="#" class="col-auto ml-auto p-0" id="deletePresetBtn">
                        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-trash p-1"
                             fill="#6a6a6a"
                             xmlns="http://www.w3.org/2000/svg">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd"
                                  d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg>
                    </a>
                </div>

                <div class="row p-2 w-100 m-auto no-gutters">
                    <div class="col"></div>

                    <div class="col">
                        {% if i.d4 %}
                        <span class="d-block text-right">
                        {{ i.d4 }} d4
                        </span>
                        {% endif %}
                        {% if i.d6 %}
                        <span class="d-block text-right">
                        {{ i.d6 }} d6
                        </span>
                        {% endif %}
                        {% if i.d8 %}
                        <span class="d-block text-right">
                        {{ i.d8 }} d8
                        </span>
                        {% endif %}
                        {% if i.d10 %}
                        <span class="d-block text-right">
                        {{ i.d10 }} d10
                        </span>
                        {% endif %}
                        {% if i.d12 %}
                        <span class="d-block text-right">
                        {{ i.d12 }} d12
                        </span>
                        {% endif %}

                        {% if i.d20 %}
                        <span class="d-block text-right">
                        {{ i.d20 }} d20
                        </span>
                        {% endif %}
                    </div>


                </div>

                <input class="w-100 position-absolute fixed-bottom main-action-btn"
                       id="roll_saved_dices"
                       type="button"
                       value="БРОСИТЬ"/>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}

</div>

{% endblock content %}

{% block integrated_js %}
{{ block.super }}
<script>

    // For result dice -------------------------
    function setEdgesValues() {
        $(".edge").each(function (key, item) {
            $(item).text(Math.floor(Math.random() * 100));
        });
        return;
    }

    function setFrontValue(roll_result) {
        $("#result").text(roll_result);
        return roll_result;
    }

    //--------------------------------------------

    // Functions for rolling presets ------------------------------
    const DICES_TYPES = [4, 6, 8, 10, 12, 20];

    // return config-object: {"d4": 0, "d6": 15, ...}
    function getPresetConfigFromInputs() {
        let config = {};
        for (let TDice of DICES_TYPES) {
            config["d" + TDice] = $("#preset_d" + TDice).val() || 0;
        }
        return config;
    }

    // ------------------------------------------------------------

    $(document).ready(function () {

        // Set random values for dice
        setEdgesValues();
        // Set result value on front edge of dice
        setFrontValue(0);

        $(".preset").each(function () {
            let chosen_preset = $(this);
            let cube_uuid = $(this).attr("cube_uuid");
            let data = {
                "csrfmiddlewaretoken": getCookie('csrftoken'),
                "cube_uuid": JSON.stringify(cube_uuid),
            };

            $(this).find("#roll_saved_dices").click(function () {
                $.post("{% url 'manage_dices:inreg_roll_dices' %}", data, function (data) {
                    if (data.dice_error) {
                        alert(data.dice_error);
                    } else {
                        $('#result').html(data.result)
                        $(".thrown-dice-container").attr("class", "thrown-dice-container thrown-dice-container-roll");
                    }
                });
                $(".thrown-dice-container").attr("class", "thrown-dice-container");
            });


            $(this).find("#deletePresetBtn").click(function (event) {
                event.preventDefault();
                $.post("{% url 'manage_dices:delete_preset' %}", data, function (data) {
                    if (data.dice_error) {
                        alert(data.dice_error);
                    }
                    chosen_preset.parent().remove();
                });
            });
        });


        $('#roll_btn').click(function () {
            let data = {
                "preset": JSON.stringify(getPresetConfigFromInputs()),
                "csrfmiddlewaretoken": getCookie('csrftoken'),
            };

            $.post("{% url 'manage_dices:inreg_roll_dices' %}", data, function (data) {
                if (data.dice_error) {
                    $('#result').html(data.result)
                    alert(data.dice_error);
                } else {
                    $('#result').html(data.result)
                    $(".thrown-dice-container").attr("class", "thrown-dice-container thrown-dice-container-roll");
                }
            });
            $(".thrown-dice-container").attr("class", "thrown-dice-container");
        });


        $('#savePresetBtn').click(function () {
            let data = {
                "preset": JSON.stringify(getPresetConfigFromInputs()),
                "csrfmiddlewaretoken": getCookie('csrftoken'),
            };

            $.post("{% url 'manage_dices:save_preset' %}", data, function (data) {
                if (data.dice_error) {
                    alert(data.dice_error);
                }
                location.reload();
            });
        });
    });
</script>
{% endblock integrated_js %}